from fpdf import FPDF
from datetime import datetime
import os

class ReportGenerator:
    def generate_analysis_report(self, data, researcher_name, researcher_id, save_path, chart_path=None):
        """Generates a professional, single-page genomic report with absolute layout."""
        pdf = FPDF()
        pdf.set_auto_page_break(auto=False) # Strictly stay on Page 1
        pdf.add_page()
        
        # --- 1. Branding & Header ---
        pdf.set_font("helvetica", "B", 16)
        pdf.set_xy(10, 10)
        pdf.cell(190, 10, "SeqAnalyzer: Genomic Bio-Intelligence Report", border=0, ln=True, align="C")
        pdf.line(10, 22, 200, 22)

        # --- 2. Researcher Metadata (FIXED: ID added) ---
        pdf.set_font("helvetica", "B", 10)
        pdf.set_xy(10, 28)
        pdf.cell(95, 7, f"Researcher: {researcher_name}", ln=0)
        pdf.cell(95, 7, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=1, align="R")
        
        # New: Researcher ID printing logic
        if researcher_id:
            pdf.set_x(10)
            pdf.cell(190, 7, f"Researcher ID: {researcher_id}", ln=True)
        
        # --- 3. Floating Chart (No collision logic) ---
        if chart_path and os.path.exists(chart_path):
            pdf.image(chart_path, x=135, y=45, w=55) 

        # --- 4. Primary Metrics (Mirrors GUI exactly) ---
        pdf.set_xy(10, 55)
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(100, 8, "[PRIMARY METRICS]", ln=True)
        pdf.set_font("helvetica", "", 10)
        
        metrics = [
            f"ID: {data['id']}",
            f"Length: {data['length']} bp",
            f"Molecular Weight: {data['weight']:.2f} Da",
            f"GC Content: {data['gc']:.2f}% (Stability: {data['stability']})",
            f"Complexity Index: {data['entropy']:.4f}",
            f"Invalid Bases: {data['invalid']}"
        ]
        for m in metrics:
            pdf.set_x(10)
            pdf.cell(100, 6, m, ln=True)

        # --- 5. Thermal Properties ---
        pdf.set_y(100)
        pdf.set_font("helvetica", "B", 11)
        pdf.set_x(10)
        pdf.cell(190, 8, "[THERMAL PROPERTIES]", ln=True)
        pdf.set_font("helvetica", "", 10)
        pdf.set_x(10)
        pdf.cell(190, 6, f"Tm Wallace: {data['tm_w']:.2f} C", ln=True)
        pdf.set_x(10)
        pdf.cell(190, 6, f"Tm Salt: {data['tm_s']:.2f} C", ln=True)

        # --- 6. Enzyme Mapping ---
        pdf.set_y(125)
        pdf.set_font("helvetica", "B", 11)
        pdf.set_x(10)
        pdf.cell(190, 8, "[ENZYME MAPPING]", ln=True)
        pdf.set_font("courier", "", 9)
        for enz, sites in data['sites'].items():
            site_str = ", ".join(map(str, sites)) if sites else "None"
            pdf.set_x(10)
            pdf.multi_cell(190, 5, f"{enz}: {site_str}")

        # --- 7. Proteomic Translation ---
        pdf.ln(5)
        pdf.set_font("helvetica", "B", 11)
        pdf.set_x(10)
        pdf.cell(190, 8, "[PROTEIN TRANSLATION]", ln=True)
        pdf.set_font("courier", "I", 9)
        prot = data['protein'][:500] + "..." if len(data['protein']) > 500 else data['protein']
        pdf.set_x(10)
        pdf.multi_cell(190, 5, prot)

        # --- 8. Footer (FIXED: Forced to bottom of Page 1) ---
        pdf.set_y(280) # Manual placement at the very bottom
        pdf.set_font("helvetica", "I", 8)
        pdf.set_x(10)
        pdf.cell(190, 10, "Generated by SeqAnalyzer", align="C")
        
        pdf.output(save_path)